Implement Memory

diff --git a/test b/test
--- a/test
+++ b/test
@@ -13,23 +13,23 @@ fi
 cd $(dirname "${0}")
 
 function test {
-    testfilepath="$1"
-    testfilebase="${testfilepath%.*}"
-    testfileext="${testfilepath##*.}"
+    filepath="$1"
+    filebase="${filepath%.*}"
+    fileext="${filepath##*.}"
 
-    printf "Test $testfilepath\n"
+    printf "Test $filepath\n"
 
-    if [ "$testfileext" != "tst" ]; then
-        printf "Invalid file extension: $testfileext\n"
+    if [ "$fileext" != "tst" ]; then
+        printf "Invalid file extension: $fileext\n"
         usage
         return 1
     fi
 
-    if [ -f "$testfilebase".asm ]; then
-        Assembler.sh "$testfilebase".asm
-        CPUEmulator.sh "$testfilepath"
+    if [ -f "$filebase".asm ]; then
+        Assembler.sh "$filebase".asm
+        CPUEmulator.sh "$filepath"
     else
-        HardwareSimulator.sh "$testfilepath"
+        HardwareSimulator.sh "$filepath"
     fi
 }
 
@@ -48,13 +48,18 @@ nocolor='\033[0m'
 for i in $(ls -d */); do
     chapter=${i%%/}
     printf "${blue}Chapter ${chapter}${nocolor}\n"
-    for testfile in $(find "$chapter" -name "*.tst"); do
-        if [ $testfile != "04/fill/Fill.tst" ]; then
-            test "$testfile"
-            if [ $? -ne 0 ]; then
-                printf "\n${red}Tests failed.${nocolor}\n"
-                exit 1
-            fi
+
+    for testfilepath in $(find "$chapter" -name "*.tst"); do
+        if [ $testfilepath = "04/fill/Fill.tst" ] || [ $testfilepath = "05/Memory.tst" ]; then
+            printf "Skip $testfilepath - Requires GUI\n"
+            continue
+        fi
+
+        test "$testfilepath"
+
+        if [ $? -ne 0 ]; then
+            printf "\n${red}Tests failed.${nocolor}\n"
+            exit 1
         fi
     done
     printf "\n"
